// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/27/2026, 6:11:05 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/home/elshimi/projects/invitation/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/elshimi/projects/invitation/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/elshimi/projects/invitation/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/elshimi/projects/invitation/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/elshimi/projects/invitation/app/plugins/**/*.{js,ts,mjs}","/home/elshimi/projects/invitation/app/composables/**/*.{js,ts,mjs}","/home/elshimi/projects/invitation/app/utils/**/*.{js,ts,mjs}","/home/elshimi/projects/invitation/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/elshimi/projects/invitation/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/elshimi/projects/invitation/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/elshimi/projects/invitation/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;