// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at ٢٧‏/٣‏/٢٠٢٦، ٣:٤٧:٠٨ ص
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/mohamedelshimi/Projects/invitation/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mohamedelshimi/Projects/invitation/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mohamedelshimi/Projects/invitation/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mohamedelshimi/Projects/invitation/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mohamedelshimi/Projects/invitation/app/plugins/**/*.{js,ts,mjs}","/Users/mohamedelshimi/Projects/invitation/app/composables/**/*.{js,ts,mjs}","/Users/mohamedelshimi/Projects/invitation/app/utils/**/*.{js,ts,mjs}","/Users/mohamedelshimi/Projects/invitation/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mohamedelshimi/Projects/invitation/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/mohamedelshimi/Projects/invitation/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/mohamedelshimi/Projects/invitation/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;